volumes:
    logs:
        driver: local
    db_data:

services:
    slim:
        image: webdevops/php-dev:8.3-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: penn
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: penn
        ports:
            - "5480:5432"
        volumes:
            - db_data:/var/lib/pgsql
            - ./docker/db_init:/docker-entrypoint-initdb.d
